### ISSUE TITLE
Uncaught TypeError: Failed to execute 'createTreeWalker' on 'Document': parameter 1 is not of typ...

### ISSUE THREAD

**Issue by daemonza** [squizlabs/atom-innerspace#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-innerspace](https://github.com/squizlabs/atom-innerspace) package, v0.1.3
### Stack Trace

Uncaught TypeError: Failed to execute 'createTreeWalker' on 'Document': parameter 1 is not of type 'Node'.

```
At /Users/wgillmer/.atom/packages/atom-innerspace/lib/atom-innerspace.coffee:0

TypeError: Failed to execute 'createTreeWalker' on 'Document': parameter 1 is not of type 'Node'.
    at TypeError (native)
    at Object.module.exports.AtomInnerspace.getTextNodes (/Users/wgillmer/.atom/packages/atom-innerspace/lib/atom-innerspace.coffee:88:23)
    at Object.module.exports.AtomInnerspace.showHiddenSpaces (/Users/wgillmer/.atom/packages/atom-innerspace/lib/atom-innerspace.coffee:54:19)
    at /Users/wgillmer/.atom/packages/atom-innerspace/lib/atom-innerspace.coffee:24:24
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:281:16
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:338:18
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:375:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:362:26
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
```
### Commands

```
  7x -7:47.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:22.4.0 core:save (atom-text-editor.editor.is-focused)
     -7:01.3.0 core:paste (atom-text-editor.editor.is-focused)
     -6:58.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -6:50.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:49.5.0 core:save (atom-text-editor.editor.is-focused)
     -4:29.1.0 core:paste (atom-text-editor.editor.is-focused)
     -4:28 core:save (atom-text-editor.editor.is-focused)
  2x -3:39 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:00.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -2:58.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:45.4.0 pane:split-right (atom-text-editor.editor.is-focused)
     -1:19.2.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:17.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:45.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:45 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "duotone-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-innerspace, v0.1.3
ctags-status, v1.3.3
duotone-dark-syntax, v0.2.0
go-plus, v3.3.12
language-docker, v1.1.3
symbols-tree-view, v0.9.3

# Dev
No dev packages
```

**Comment by sertand** [comment]
You should no longer get this error with the latest version (v0.1.4)
